spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test3
    username: sa
    password:

jwt:
  access-secret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkey
  refresh-secret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
  access-expiration: 600000  # 10 min: 10min * 60 sec * 1000 millisecond
  refresh-expiration: 10800000  # 10800000 3 hours: 3hours * 60min * 60sec * 1000 millisecond
  secretKey: U2VjdXJlU2VjcmV0S2V5VGhhdElzU3VwZXJSYW5kb21BbmRDb21wbGV4



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace